name: feature_tooltip
description: >
  A Flutter package that provides an advanced tooltip with custom positioning,
  styling, animations, extended display durations, and optional background
  blurring. This widget can be used to replace the default Tooltip widget and
  offers more flexibility for building tooltips in your apps.
version: 0.0.1
repository: https://github.com/jatinchaudhary/feature_tooltip
issue_tracker: https://github.com/jatinchaudhary/feature_tooltipissues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true